packages:
  - packages/*
  - integration/*
  - playwright
overrides:
  dompurify@>=3.1.3 <=3.3.1: '>=3.3.2'
  typescript-cp>tar: '>=7.5.11'

patchedDependencies:
  monaco-editor: patches/monaco-editor.patch

preferWorkspacePackages: true

publicHoistPattern:
  - eslint
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200  # minutes (30 days)
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
- '@axonivy/*'
