packages:
  - packages/*
  - integration/*
  - playwright
preferWorkspacePackages: true
publicHoistPattern:
  - eslint
  - '@codingame/monaco-vscode-extension-api'
  - '@codingame/monaco-vscode-editor-api'
overrides:
  'vscode': 'npm:@codingame/monaco-vscode-extension-api@^23.2'
  'monaco-editor': 'npm:@codingame/monaco-vscode-editor-api@^23.2'
