package net.webservicex.client;

import javax.annotation.Generated;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.6.4
 * 2024-11-05T13:34:00.270+01:00
 * Generated source version: 3.6.4
 *
 */
@WebService(targetNamespace = "http://www.webservicex.net/", name = "GeoIPServiceSoap")
@XmlSeeAlso({org.w3._2001.xmlschema.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-11-05T13:34:00.270+01:00", comments = "Apache CXF 3.6.4")
public interface GeoIPServiceSoap {

    /**
     * GeoIPService - GetGeoIP enables you to easily look up countries by IP addresses
     */
    @WebMethod(operationName = "GetGeoIP", action = "http://www.webservicex.net/GetGeoIP")
    @WebResult(name = "GetGeoIPResponse", targetNamespace = "http://www.webservicex.net/", partName = "parameters")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-11-05T13:34:00.270+01:00")
    public GetGeoIPResponse getGeoIP(

        @WebParam(partName = "parameters", name = "GetGeoIP", targetNamespace = "http://www.webservicex.net/")
        GetGeoIP parameters
    );

    /**
     * GeoIPService - GetGeoIPContext enables you to easily look up countries by Context
     */
    @WebMethod(operationName = "GetGeoIPContext", action = "http://www.webservicex.net/GetGeoIPContext")
    @WebResult(name = "GetGeoIPContextResponse", targetNamespace = "http://www.webservicex.net/", partName = "parameters")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-11-05T13:34:00.270+01:00")
    public GetGeoIPContextResponse getGeoIPContext(

        @WebParam(partName = "parameters", name = "GetGeoIPContext", targetNamespace = "http://www.webservicex.net/")
        GetGeoIPContext parameters
    );
}
