package net.webservicex.client;

import javax.annotation.Generated;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.6.4
 * 2024-11-05T13:34:00.327+01:00
 * Generated source version: 3.6.4
 *
 */
@WebService(targetNamespace = "http://www.webservicex.net/", name = "GeoIPServiceHttpPost")
@XmlSeeAlso({org.w3._2001.xmlschema.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-11-05T13:34:00.327+01:00", comments = "Apache CXF 3.6.4")
public interface GeoIPServiceHttpPost {

    /**
     * GeoIPService - GetGeoIP enables you to easily look up countries by IP addresses
     */
    @WebMethod(operationName = "GetGeoIP")
    @WebResult(name = "GeoIP", targetNamespace = "http://www.webservicex.net/", partName = "Body")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-11-05T13:34:00.327+01:00")
    public GeoIP getGeoIP(

        @WebParam(partName = "IPAddress", name = "IPAddress", targetNamespace = "http://www.webservicex.net/")
        java.lang.String ipAddress
    );

    /**
     * GeoIPService - GetGeoIPContext enables you to easily look up countries by Context
     */
    @WebMethod(operationName = "GetGeoIPContext")
    @WebResult(name = "GeoIP", targetNamespace = "http://www.webservicex.net/", partName = "Body")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-11-05T13:34:00.327+01:00")
    public GeoIP getGeoIPContext()
;
}
