package net.webservicex.client;

import java.net.URL;
import javax.annotation.Generated;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.6.4
 * 2024-11-05T13:34:00.339+01:00
 * Generated source version: 3.6.4
 *
 */
@WebServiceClient(name = "GeoIPService",
                  wsdlLocation = "geoipservice.wsdl",
                  targetNamespace = "http://www.webservicex.net/")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-11-05T13:34:00.339+01:00", comments = "Apache CXF 3.6.4")
public class GeoIPService extends Service {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-11-05T13:34:00.339+01:00")
    public static final URL WSDL_LOCATION;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-11-05T13:34:00.339+01:00")
    public static final QName SERVICE = new QName("http://www.webservicex.net/", "GeoIPService");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-11-05T13:34:00.339+01:00")
    public static final QName GeoIPServiceSoap = new QName("http://www.webservicex.net/", "GeoIPServiceSoap");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-11-05T13:34:00.339+01:00")
    public static final QName GeoIPServiceSoap12 = new QName("http://www.webservicex.net/", "GeoIPServiceSoap12");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-11-05T13:34:00.339+01:00")
    public static final QName GeoIPServiceHttpGet = new QName("http://www.webservicex.net/", "GeoIPServiceHttpGet");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-11-05T13:34:00.339+01:00")
    public static final QName GeoIPServiceHttpPost = new QName("http://www.webservicex.net/", "GeoIPServiceHttpPost");
    static {
        URL url = GeoIPService.class.getResource("geoipservice.wsdl");
        if (url == null) {
            url = GeoIPService.class.getClassLoader().getResource("geoipservice.wsdl");
        }
        if (url == null) {
            java.util.logging.Logger.getLogger(GeoIPService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "geoipservice.wsdl");
        }
        WSDL_LOCATION = url;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-11-05T13:34:00.339+01:00")
    public GeoIPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-11-05T13:34:00.339+01:00")
    public GeoIPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-11-05T13:34:00.339+01:00")
    public GeoIPService() {
        super(WSDL_LOCATION, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-11-05T13:34:00.339+01:00")
    public GeoIPService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-11-05T13:34:00.339+01:00")
    public GeoIPService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-11-05T13:34:00.339+01:00")
    public GeoIPService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns GeoIPServiceSoap
     */
    @WebEndpoint(name = "GeoIPServiceSoap")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-11-05T13:34:00.339+01:00")
    public GeoIPServiceSoap getGeoIPServiceSoap() {
        return super.getPort(GeoIPServiceSoap, GeoIPServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GeoIPServiceSoap
     */
    @WebEndpoint(name = "GeoIPServiceSoap")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-11-05T13:34:00.339+01:00")
    public GeoIPServiceSoap getGeoIPServiceSoap(WebServiceFeature... features) {
        return super.getPort(GeoIPServiceSoap, GeoIPServiceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns GeoIPServiceSoap
     */
    @WebEndpoint(name = "GeoIPServiceSoap12")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-11-05T13:34:00.339+01:00")
    public GeoIPServiceSoap getGeoIPServiceSoap12() {
        return super.getPort(GeoIPServiceSoap12, GeoIPServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GeoIPServiceSoap
     */
    @WebEndpoint(name = "GeoIPServiceSoap12")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-11-05T13:34:00.339+01:00")
    public GeoIPServiceSoap getGeoIPServiceSoap12(WebServiceFeature... features) {
        return super.getPort(GeoIPServiceSoap12, GeoIPServiceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns GeoIPServiceHttpGet
     */
    @WebEndpoint(name = "GeoIPServiceHttpGet")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-11-05T13:34:00.339+01:00")
    public GeoIPServiceHttpGet getGeoIPServiceHttpGet() {
        return super.getPort(GeoIPServiceHttpGet, GeoIPServiceHttpGet.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GeoIPServiceHttpGet
     */
    @WebEndpoint(name = "GeoIPServiceHttpGet")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-11-05T13:34:00.339+01:00")
    public GeoIPServiceHttpGet getGeoIPServiceHttpGet(WebServiceFeature... features) {
        return super.getPort(GeoIPServiceHttpGet, GeoIPServiceHttpGet.class, features);
    }


    /**
     *
     * @return
     *     returns GeoIPServiceHttpPost
     */
    @WebEndpoint(name = "GeoIPServiceHttpPost")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-11-05T13:34:00.339+01:00")
    public GeoIPServiceHttpPost getGeoIPServiceHttpPost() {
        return super.getPort(GeoIPServiceHttpPost, GeoIPServiceHttpPost.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GeoIPServiceHttpPost
     */
    @WebEndpoint(name = "GeoIPServiceHttpPost")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-11-05T13:34:00.339+01:00")
    public GeoIPServiceHttpPost getGeoIPServiceHttpPost(WebServiceFeature... features) {
        return super.getPort(GeoIPServiceHttpPost, GeoIPServiceHttpPost.class, features);
    }

}
