# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0-dev/config/databases.json
Databases:
  test:
    Url: jdbc:h2:mem:test
    Driver: org.hsqldb.jdbc.JDBCDriver
    Icon: res:/webContent/icons/Developer.jpg
