# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0-dev/config/rest-clients-1.json
RestClients:
  test:
    Name: test
    Url: http://localhost/
    Features:
      - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
    LegacyUUID: d319aec9-4d1f-49a2-b859-ce8854b3091a
  #This is a generize fake client
  genderize:
    Name: genderize
    Url: http://localhost/
    Icon: res:/webContent/icons/genderize.png
    Features:
      - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
    LegacyUUID: b68bfe16-1f2d-43e6-be37-9a85e1aeaf79
